### ISSUE TITLE
Size of MNIST CIFAR dataset 10k instead of expected 50k 

### ISSUE THREAD

**Issue by mpagli** [harshays/simplicitybiaspitfalls#1]
In the paper, the MNIST CIFAR10 dataset is described as having 50k training samples: "The training and test datasets comprise 50,000 and 10,000 images of size 3 × 64 × 32". When running the script in the notebook `02_extremeSB_mnistcifar_data.ipynb`, the training dataset is of size 10k or so. Am I doing something wrong?

**Comment by harshays** [comment]
Sorry for the confusion, that statement in the paper is incorrect. CIFAR-10 and MNIST have 50k train images in total (~5k per class) and MNIST-CIFAR is a binary classification task, so the MNIST-CIFAR training dataset size is ~10k.

**Comment by mpagli** [comment]
Thanks for the clarification!
