### ISSUE TITLE
Poster link broken

### ISSUE THREAD

**Issue by dymil** [harshays/simplicitybiaspitfalls#3]
The poster link to Google Drive in the README produces "Page Not Found", and unfortunately the Internet Archive Wayback Machine [didn't back it up](https://web.archive.org/web/20220000000000*/https://drive.google.com/file/d/10McXcIyTM8pxJE2edqcvO2cBxmq8is2P/view?usp=sharing) either.

**Comment by harshays** [comment]
Sorry about that, here's the poster: http://harshay.me/pdf/poster_neurips20_simplicitybias.pdf
